const permissions = {
  church: {
    create: "CREATE_CHURCH",
    update: "UPDATE_CHURCH",
    delete: "DELETE_CHURCH",
    view: "VIEW_CHURCH",
  },
  request: {
    send: "SEND_REQUEST",
  },
  churchRequest: {
    accept: "ACCEPT_REQUEST",
    reject: "REJECT_REQUEST",
    delete: "DELETE_REQUEST",
  },
  level: {
    create: "CREATE_LEVEL",
    update: "UPDATE_LEVEL",
    delete: "DELETE_LEVEL",
  },
  churchLevel: {
    add: "ADD_LEVEL",
    remove: "REMOVE_LEVEL",
  },
  role: {
    create: "CREATE_ROLE",
    update: "UPDATE_ROLE",
    delete: "DELETE_ROLE",
  },
  member: {
    create: "CREATE_MEMBER",
    update: "UPDATE_MEMBER",
    delete: "DELETE_MEMBER",
    view: "VIEW_MEMBER",
  },
  event: {
    create: "CREATE_EVENT",
    update: "UPDATE_EVENT",
    delete: "DELETE_EVENT",
  },
  group: {
    create: "CREATE_GROUP",
    update: "UPDATE_GROUP",
    delete: "DELETE_GROUP",
  },
  groupMember: {
    add: "ADD_MEMBER",
    remove: "REMOVE_MEMBER",
  },
  groupEvent: {
    add: "ADD_EVENT",
    remove: "REMOVE_EVENT",
  },
  me: {
    update: "UPDATE_ME",
    delete: "DELETE_ME",
  },
  user: {
    viewChurch: "VIEW_CHURCH",
    viewMember: "VIEW_MEMBER",
    viewEvent: "VIEW_EVENT",
    viewGroup: "VIEW_GROUP",
    viewAdmin: "VIEW_ADMIN",
  },
};
const defaultRoles = (isHq, churchId) => {
  const roles = [
    {
      name: "Admin",
      church: churchId,
      description: "Admin can perform all actions except creating levels",
      permissions: [
        permissions.church.create,
        permissions.church.update,
        permissions.church.delete,
        permissions.church.view,
        permissions.request.send,
        permissions.churchRequest.accept,
        permissions.churchRequest.reject,
        permissions.churchRequest.delete,
        permissions.role.create,
        permissions.role.update,
        permissions.role.delete,
        permissions.member.create,
        permissions.member.update,
        permissions.member.delete,
        permissions.member.view,
        permissions.event.create,
        permissions.event.update,
        permissions.event.delete,
        permissions.group.create,
        permissions.group.update,
        permissions.group.delete,
        permissions.groupMember.add,
        permissions.groupMember.remove,
        permissions.groupEvent.add,
        permissions.groupEvent.remove,
        permissions.me.update,
        permissions.me.delete,
        permissions.user.viewChurch,
        permissions.user.viewMember,
        permissions.user.viewEvent,
        permissions.user.viewGroup,
        permissions.user.viewAdmin,
      ],
    },
    {
      name: "Member",
      church: churchId,
      description: "Member can only view and update their own profile",
      permissions: [
        permissions.church.view,
        permissions.me.update,
        permissions.me.delete,
        permissions.user.viewChurch,
        permissions.user.viewMember,
        permissions.user.viewEvent,
        permissions.user.viewGroup,
      ],
    },
    {
      name: "Editor",
      // Editor can only update and delete members
      church: churchId,
      description: "Editor can only update and delete members",
      permissions: [
        permissions.member.update,
        permissions.member.delete,
        permissions.me.update,
        permissions.me.delete,
        permissions.user.viewChurch,
        permissions.user.viewMember,
        permissions.user.viewEvent,
        permissions.user.viewGroup,
        permissions.user.viewAdmin,
      ],
    },
    {
      name: "User",
      // User can only view the church and members
      church: churchId,
      description: "User can only view the church and members",
      permissions: [
        permissions.church.view,
        permissions.member.view,
        permissions.me.update,
        permissions.me.delete,
        permissions.user.viewChurch,
        permissions.user.viewMember,
        permissions.user.viewEvent,
        permissions.user.viewGroup,
        permissions.user.viewAdmin,
      ],
    },
  ];

  if (isHq) {
    roles.push({
      name: "Super Admin",
      description: "Super Admin can perform all actions",
      church: churchId,
      permissions: [
        permissions.church.create,
        permissions.church.update,
        permissions.church.delete,
        permissions.church.view,
        permissions.request.send,
        permissions.churchRequest.accept,
        permissions.churchRequest.reject,
        permissions.churchRequest.delete,
        permissions.churchLevel.add,
        permissions.churchLevel.remove,
        permissions.role.create,
        permissions.role.update,
        permissions.role.delete,
        permissions.member.create,
        permissions.member.update,
        permissions.member.delete,
        permissions.member.view,
        permissions.event.create,
        permissions.event.update,
        permissions.event.delete,
        permissions.group.create,
        permissions.group.update,
        permissions.group.delete,
        permissions.groupMember.add,
        permissions.groupMember.remove,
        permissions.groupEvent.add,
        permissions.groupEvent.remove,
        permissions.me.update,
        permissions.me.delete,
        permissions.user.viewChurch,
        permissions.user.viewMember,
        permissions.user.viewEvent,
        permissions.user.viewGroup,
        permissions.user.viewAdmin,
      ],
    });
  }

  return roles;
};
module.exports = {
  permissions,
  defaultRoles,
};
